<template>
    <el-container>
        <el-header></el-header>
        <el-container>
            <el-aside></el-aside>
            <el-main></el-main>
        </el-container>
    </el-container>
</template>